using UnityEngine;
using System.Collections.Generic;

namespace VoxelLUT {

    /**
     * Abstract class which all block rendering types will
     * extend. Has some default helper functionality and forces
     * blocks to implement certain functions.
     */
    public abstract class BlockVisual {

        /**
         * This represents the default voxel type with rounded edges
         * look during rendering
         */
        protected static readonly int[] _DEFAULT_TRIANGLES =
        {
            // top triangles
            Up.v1.Index(), Up.v2.Index(), Up.v3.Index(),
            Up.v1.Index(), Up.v3.Index(), Up.v4.Index(),
            // bottom triangles
            Down.v1.Index(), Down.v2.Index(), Down.v3.Index(),
            Down.v1.Index(), Down.v3.Index(), Down.v4.Index(),
            // left triangles
            Left.v1.Index(), Left.v2.Index(), Left.v3.Index(),
            Left.v1.Index(), Left.v3.Index(), Left.v4.Index(),
            // right triangles
            Right.v1.Index(), Right.v2.Index(), Right.v3.Index(),
            Right.v1.Index(), Right.v3.Index(), Right.v4.Index(),
            // front triangles
            Front.v1.Index(), Front.v2.Index(), Front.v3.Index(),
            Front.v1.Index(), Front.v3.Index(), Front.v4.Index(),
            // back triangles
            Back.v1.Index(), Back.v2.Index(), Back.v3.Index(),
            Back.v1.Index(), Back.v3.Index(), Back.v4.Index()
        };

        public abstract int[] Triangles { get; }

        /**
         * Fill the provided array with triangle data
         */
        public void FillTriangles(List<int> tris, int offset) {
            int[] triangles = Triangles;
            int len = triangles.Length;

            if (len == 0) {
                return;
            }

            for (int i = 0; i < len; i++) {
                tris.Add(triangles[i] + offset);
            }
        }

        /**
         * Get the number of triangles that is being generated by this
         * particular block
         */
        public int Count {
            get {
                return Triangles.Length;
            }
        }

        /**
         * Quick index accessor as an array
         */
        public int this[int index] { 
            get {
                return Triangles[index];
            }
        }

        /**
         * Can be used to quickly visualize the triangles as Gizmos. Only
         * available in Editor mode. Function will be empty once code has been built
         */
        public void OnDebug() {
#if UNITY_EDITOR
            Color oldColor = Gizmos.color;
            Gizmos.color = Color.blue;

            int[] tris = Triangles;

            for (int i = 0; i < tris.Length; i+=3) {
                Gizmos.DrawLine(Block.Get(tris[i]), Block.Get(tris[i + 1]));
                Gizmos.DrawLine(Block.Get(tris[i + 1]), Block.Get(tris[i + 2]));
                Gizmos.DrawLine(Block.Get(tris[i + 2]), Block.Get(tris[i]));
            }

            Gizmos.color = Color.green;

            for (int i = 0; i < tris.Length; i ++) {
                Gizmos.DrawSphere(Block.Get(tris[i]), 0.02f);
            }

            Gizmos.color = oldColor;
#endif
        }
    }
}
